async function testNotif() {
  try {
    const loginRes = await fetch('http://localhost:8080/api/auth/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: 'admin@progressiq.local', password: 'ChangeMe123!' })
    });
    const loginData = await loginRes.json();
    const token = loginData.token;
    
    // Get a user to send to (let's find the first student)
    const usersRes = await fetch('http://localhost:8080/api/admin/users?role=STUDENT', {
      headers: { Authorization: `Bearer ${token}` }
    });
    const usersData = await usersRes.json();
    
    const student = usersData.users[0];
    if (!student) return console.log('No students found to test notification.');
    
    console.log(`Sending test notification with email to user: ${student.email}`);
    
    // Trigger notification WITH email
    const notifRes = await fetch('http://localhost:8080/api/notifications', {
      method: 'POST',
      headers: { 
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}` 
      },
      body: JSON.stringify({
        userId: student._id,
        title: 'Test Email Dispatch & Notification',
        message: 'This is a test notification generated by the system to verify email dispatch logs.',
        type: 'INFO',
        link: '/student/dashboard',
        sendEmail: true
      })
    });
    const notifData = await notifRes.json();
    
    console.log('Notification API response:', notifData);
    console.log('Check backend dev server console for email logs now.');
  } catch(e) {
    console.error('Failed test:', e.message);
  }
}

testNotif();
